name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: cargo test --verbose
    - name: Build optimized binary
      run: cargo build --release
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
